# Site
locale: "en-US"
title: "Sanvesh Srivastava"
description: "Associate Professor, Statistics and Actuarial Science, University of Iowa"
url: "https://blayes.github.io"
baseurl: ""
repository: "blayes/blayes.github.io"
timezone: "America/Chicago"

# Author
author:
  name: "Sanvesh Srivastava"
  avatar: "sanvesh.png"
  bio: "Associate Professor in the Department of Statistics and Actuarial Science, The University of Iowa"
  location: "Iowa City, IA"
  email: "sanvesh-srivastava@uiowa.edu"
  github: "blayes"
  googlescholar: "https://scholar.google.com/citations?user=BR_89wIAAAAJ&hl=en"
  orcid: "https://orcid.org/0000-0002-5483-9579"

# Build
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: "/:categories/:title/"

# Collections
collections:
  teaching:      { output: true, permalink: "/:collection/:path/" }
  publications:  { output: true, permalink: "/:collection/:path/" }
  portfolio:     { output: true, permalink: "/:collection/:path/" }
  talks:         { output: true, permalink: "/:collection/:path/" }

# Defaults
defaults:
  - scope: { path: "", type: posts }        ; values: { layout: single, author_profile: true }
  - scope: { path: "", type: pages }        ; values: { layout: single, author_profile: true }
  - scope: { path: "", type: teaching }     ; values: { layout: single, author_profile: true }
  - scope: { path: "", type: publications } ; values: { layout: single, author_profile: true }
  - scope: { path: "", type: portfolio }    ; values: { layout: single, author_profile: true }
  - scope: { path: "", type: talks }        ; values: { layout: talk,   author_profile: true }

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-redirect-from
  - jemoji

# Include / Exclude
include: ["_pages", "files"]
exclude: ["node_modules", "vendor", "Gemfile", "Gemfile.lock"]

# Optional
compress_html:
  clippings: all
  ignore: { envs: development }
